# Generated by Django 4.1.3 on 2022-11-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_projects_github_link_projects_project_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack_name', models.CharField(blank=True, max_length=50, null=True)),
                ('stack_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('project', models.ManyToManyField(to='api.projects')),
            ],
        ),
    ]
