# Generated by Django 4.1.3 on 2022-11-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='project',
        ),
        migrations.AddField(
            model_name='projects',
            name='stack',
            field=models.ManyToManyField(to='api.stack'),
        ),
        migrations.AddField(
            model_name='stack',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
