# Generated by Django 4.1.3 on 2022-11-23 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_stack_project_projects_stack_stack_is_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='images',
            new_name='image',
        ),
        migrations.CreateModel(
            name='ProjectSlideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('alt', models.CharField(blank=True, max_length=200, null=True)),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.projects')),
            ],
        ),
    ]
