# Generated by Django 4.0.5 on 2022-12-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_stack_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='stack',
        ),
    ]
