# Generated by Django 4.0.5 on 2022-12-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_projects_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='stack',
            field=models.ManyToManyField(to='api.stack'),
        ),
    ]
