# Generated by Django 4.0.5 on 2022-12-02 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_projects_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='stack',
        ),
        migrations.AddField(
            model_name='stack',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.projects'),
        ),
    ]
