# Generated by Django 4.0.5 on 2022-12-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_projects_stack_stack_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='project_id',
        ),
        migrations.AddField(
            model_name='stack',
            name='projects',
            field=models.ManyToManyField(to='api.projects'),
        ),
    ]
