# Generated by Django 4.0.5 on 2022-12-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_stack_project_id_stack_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='projects',
        ),
        migrations.AddField(
            model_name='projects',
            name='stack',
            field=models.ManyToManyField(to='api.stack'),
        ),
    ]
