# Generated by Django 4.0.5 on 2022-12-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_stack_projects_projects_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='stack',
        ),
    ]
