# Generated by Django 4.0.5 on 2023-01-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_projects_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='stack',
            field=models.ManyToManyField(related_name='stack', to='api.stack'),
        ),
    ]
